export default {
  header: {
    home: 'Home',
    about: 'about',
    shop: 'shop',
    contact: 'contact',
    cart: 'Cart',
  },
  about: {
    title: 'Unique Porcelain',
    collection: 'Collection',
    unique: 'Unique & modern pottery made by our master in porcelain & stones',
    shop: 'Shop collection',
  },
  workspace: {
    categories: 'product categories',
    porcelain: 'Porcelain',
    pottery: 'Pottery',
    unique: 'Unique & modern pottery made by our master in porcelain & stones',
    vases: 'vases',
    mugs: 'mugs',
    plates: 'plates',
    hand: 'Hand Grafted Pottery since 1990',
    handInfo: 'Handcrafted pottery is unique & beautiful, made by skilled artisans who take pride in their work. Every step is done by hand, resulting in functional pieces with their own unique character. Perfect for a stunning vase, plates, or unique gift. Appreciate the beauty of handmade items.',
    provide: 'We Provide Premium Pottery Produts',
    provideInfo: 'We offer premium pottery products crafted with care and attention to detail. Made with high-quality materials & traditional techniques, each piece is beautiful and functional. Perfect for a stunning vase, plates, or unique gift. Experience the beauty and quality today.',
  },
  ceramics: {
    orange: 'Orange Ceramic',
    orangeInfo: 'Orange ceramic adds warmth & energy to any space. Handcrafted by skilled artisans, each piece is unique & eye-catching. A beautiful & functional work of art. Experience the beauty of orange ceramic today.',
    gold: 'Gold & Black Pottery',
    goldInfo: 'Gold & Black Pottery is a luxurious & sophisticated choice. Meticulously handcrafted by skilled artisans. Stunning statement pieces & unique gifts. Experience the beauty & luxury today.',
    details: 'View Details',
    featured: 'Featured Products',
  },
  collection: {
    store: 'OUR ONLINE STORE',
    collection: 'Pottery collection',
    cartButton: 'add to cart',
    done: 'done',
    view: 'View all products',
  },
  banner: {
    ready: 'Ready to start shopping?',
    text: 'Are you ready to start shopping? Let\'s find some amazing deals and fill up your cart with all the things you\'ve been wanting',
    new: 'new collection',
  },
  subscribe: {
    latest: 'Latest newsData',
    news: 'New updates',
    placeholder: 'Enter your email',
    subscribe: 'subscribe',
    message: 'Subscribe to our newsletter',
  },
  cart: {
    low: 'lowest first',
    high: 'highest first',
    search: 'Search by name',
    buy: 'buy',
    total: 'Total',
    empty: 'Sorry, your shopping cart is currently empty.',
    discount: 'Use discount',
    remove: 'remove',
  },
};
